export const apiUrl = "https://alextraveylan.pythonanywhere.com"
// export const apiUrl = "http://localhost:5000"
export const questionsUrl = `${apiUrl}/question`
export const submitUrl = `${apiUrl}/submit`
export const emailUrl = `${apiUrl}/send_email`
export const firstVersionUrl = `${apiUrl}/first_version`
export const reflexionUrl = `${apiUrl}/reflexion`
export const nbPropositionsUrl = `${apiUrl}/get_nb_propositions`
export const checkUrl = `${apiUrl}/check`
export const comboUrl = `${apiUrl}/get_combo`
export const historyUrl = `${apiUrl}/get_history`
